// Needs ionicons, which is NOT a dependency of this repo (it would change pnpm-lock.yaml).
// Run with a temp install:  npm i --no-save --prefix /tmp/ion ionicons@8.1.0 && ION=/tmp/ion node scripts/build-icons.mjs
// (or `npx -p ionicons@8.1.0` and point ION at its node_modules parent).
// Builds src/components/dashboard/kit/icons/paths.ts from the Ionicons SVGs
// listed in scripts/icons.json. Run: node scripts/build-icons.mjs
// ionicons is a devDependency only: the generated file is committed, so the
// site never fetches icons at runtime and the CSP needs nothing new.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
// ionicons restricts package exports, so walk up to find node_modules/ionicons.
let pkgDir = null;
if (process.env.ION && existsSync(join(process.env.ION, "node_modules", "ionicons"))) pkgDir = join(process.env.ION, "node_modules", "ionicons");
for (let dir = here; !pkgDir && dir !== dirname(dir); dir = dirname(dir)) {
  const candidate = join(dir, "node_modules", "ionicons");
  if (existsSync(candidate)) { pkgDir = candidate; break; }
}
if (!pkgDir) throw new Error("ionicons is not installed");
const names = JSON.parse(readFileSync(join(here, "icons.json"), "utf8"));

const entries = [];
for (const name of names) {
  const file = join(pkgDir, "dist", "svg", `${name}.svg`);
  if (!existsSync(file)) throw new Error(`Missing Ionicon: ${name}`);
  const svg = readFileSync(file, "utf8").trim();
  const inner = svg.replace(/^<svg[^>]*>/, "").replace(/<\/svg>$/, "");
  entries.push(`  ${JSON.stringify(name)}: ${JSON.stringify(inner)},`);
}

const out = `// GENERATED by scripts/build-icons.mjs from scripts/icons.json. Do not edit.
// Ionicons (MIT). Add a name to icons.json and re-run the script.
export const ICON_PATHS = {
${entries.join("\n")}
} as const;

export type IconName = keyof typeof ICON_PATHS;
`;
writeFileSync(join(here, "..", "src/components/dashboard/kit/icons/paths.ts"), out);
console.log(`Wrote ${names.length} icons`);
